DROP TABLE STAFF;
CREATE TABLE STAFF(
    SNO VARCHAR2(15 BYTE) NOT NULL,
    NAME VARCHAR2(65 BYTE),
    DEPT VARCHAR2(40 BYTE) NOT NULL,
    SALARY NUMBER NOT NULL
);

ALTER TABLE STAFF
    ADD CONSTRAINT PK_SNO
        PRIMARY KEY(SNO);